CREATE DATABASE IF NOT EXISTS eccube CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'eccube'@'%' IDENTIFIED BY 'eccube';
GRANT ALL PRIVILEGES ON eccube.* TO 'eccube'@'%';
FLUSH PRIVILEGES;