parameters:
    env(DATABASE_URL): ''
    env(DATABASE_SERVER_VERSION): ~
    env(DATABASE_CHARSET): 'utf8'

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: "%env(DATABASE_SERVER_VERSION)%"
                charset: '%env(DATABASE_CHARSET)%'

                default_table_options:
                    charset: 'utf8mb4'
                    collation: 'utf8mb4_bin'

                url: '%env(DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                NORMALIZE: Eccube\Doctrine\ORM\Query\Normalize
            numeric_functions:
                EXTRACT: Eccube\Doctrine\ORM\Query\Extract
        filters:
            option_nostock_hidden:
                class: Eccube\Doctrine\Filter\NoStockHiddenFilter
                enabled: false
            incomplete_order_status_hidden:
                class: Eccube\Doctrine\Filter\OrderStatusFilter
                enabled: false
        mappings:
            Customize:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/app/Customize/Entity'
                prefix: 'Customize\Entity'
                alias: Customize
