monolog:
    channels: ["front", "admin"]

    handlers:
        front:
            type: stream
            path: "%kernel.logs_dir%/front.log"
            level: debug
            channels: ["front"]
