name: EC-CUBE CI
on:
  push:
    branches: [main, customize]
  pull_request:
    branches: [main, customize]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: eccube
          MYSQL_USER: eccube
          MYSQL_PASSWORD: eccube
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, pdo, pdo_mysql, intl, zip
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Composer dependencies
        working-directory: ./html
        run: composer install
      - name: Download simple-phpunit
        working-directory: ./html
        run: vendor/bin/simple-phpunit install
      - name: Install EC-CUBE
        working-directory: ./html
        run: php bin/console eccube:install --no-interaction
      - name: Clear cache after install
        working-directory: ./html
        run: php bin/console cache:clear
      - name: Run PHPUnit tests
        working-directory: ./html
        run: vendor/bin/simple-phpunit -c phpunit.custom.xml
